<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/auth.proto

namespace GPBMetadata\Proto;

class Auth
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abb010a1070726f746f2f617574682e70726f746f221c0a0c48656c6c6f" .
            "52657175657374120c0a046e616d65180120012809221d0a0a48656c6c6f" .
            "5265706c79120f0a076d65737361676518012001280932620a0747726565" .
            "74657212280a0853617948656c6c6f120d2e48656c6c6f52657175657374" .
            "1a0b2e48656c6c6f5265706c792200122d0a0d53617948656c6c6f416761" .
            "696e120d2e48656c6c6f526571756573741a0b2e48656c6c6f5265706c79" .
            "2200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

